### ISSUE TITLE
About Hydra Hydra's exception formatting:

### ISSUE THREAD

**Issue by Sonerberat** [NKI-AI/STAPLER#4]
Traceback (most recent call last):
  File "/home/soner/STAPLER/tools/pretrain.py", line 39, in <module>
    main()
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/hydra/_internal/utils.py", line 301, in run_and_report
    raise ex
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/hydra/core/utils.py", line 116, in run_job
    output_dir = str(OmegaConf.select(config, job_dir_key))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 682, in select
    format_and_raise(node=cfg, key=key, value=None, cause=e, msg=str(e))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 674, in select
    return select_value(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/_impl.py", line 58, in select_value
    node = select_node(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/_impl.py", line 93, in select_node
    _root, _last_key, node = cfg._select_impl(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 531, in _select_impl
    value = root._maybe_resolve_interpolation(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 921, in accept
    return visitor.visitInterpolationNode(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 745, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 664, in _resolve_node_interpolation
    parent, last_key, value = root_node._select_impl(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 531, in _select_impl
    value = root._maybe_resolve_interpolation(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 921, in accept
    return visitor.visitInterpolationNode(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 745, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 664, in _resolve_node_interpolation
    parent, last_key, value = root_node._select_impl(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 531, in _select_impl
    value = root._maybe_resolve_interpolation(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 769, in resolve_parse_tree
    raise InterpolationResolutionError(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 298, in visitText
    return self.visitInterpolation(c)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1041, in accept
    return visitor.visitInterpolationResolver(self)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 179, in visitInterpolationResolver
    return self.resolver_interpolation_callback(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 750, in resolver_interpolation_callback
    return self._evaluate_custom_resolver(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/base.py", line 694, in _evaluate_custom_resolver
    return resolver(
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 445, in resolver_wrapper
    ret = resolver(*args, **kwargs)
  File "/home/soner/anaconda3/envs/Stapler/lib/python3.9/site-packages/omegaconf/resolvers/oc/__init__.py", line 38, in env
    raise KeyError(f"Environment variable '{key}' not found")
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable 'PROJECT_ROOT' not found"
    full_key: hydra.run.dir
    object_type=dict
    

To whom may concern,
I do not why but I am facing this error. I could not find any solution in the web.
Best Regards,

**Comment by bpkwee** [comment]
from this message: `Environment variable 'PROJECT_ROOT' not found`
it seems like you have not setup your .env file properly.

You need to adapt the following file to your system, and change the filename from `env.example` to `.env` https://github.com/NKI-AI/STAPLER/blob/main/tools/env.example

**Comment by bpkwee** [comment]
Since the readme describes the usage of .env I will be closing this issue. If you run into anything else, feel free to open a new issue.
